const analyseKeyword = () => {};
const analyseContent = () => {};
const analyseCompetitor = () => {};
const analyseBacklinks = () => {};
const rankKeywords = () => {};
const checkDomainAuthority = () => {};
const serpPreview = () => {};
const seoScore = () => {};
const optimisePage = () => {};